import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { T } from '../styles/tokens';
import { useAutoSave } from '../hooks/useAutoSave';
import { useIsMobile } from '../hooks/useIsMobile';
import Header from '../components/Header';
import DayInput from '../components/DayInput';
import { getReport, updateReport, addDayToReport, updateDayInReport } from '../lib/db';
import { supabase } from '../lib/supabase';
import { generateAutoDay, getReportStats, formatDate } from '../utils/helpers';

export default function ReportEditor() {
  const { reportId } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const isMobile = useIsMobile();

  useEffect(() => {
    const initializeReport = async () => {
      const { data: sessionData } = await supabase.auth.getSession();
      setUser(sessionData?.session?.user);

      if (reportId) {
        try {
          const existingReport = await getReport(reportId);
          setReport(existingReport);
        } catch (error) {
          console.error('Failed to load report:', error);
        }
      }

      setLoading(false);
    };

    initializeReport();
  }, [reportId]);

  const saveStatus = useAutoSave(
    report,
    async (dataToSave) => {
      if (!user || !dataToSave || !reportId) return;
      await updateReport(reportId, dataToSave);
    },
    900
  );

  const handleDayUpdate = async (dayIndex, updatedDay) => {
    if (!report) return;

    const updatedReport = { ...report };
    updatedReport.days[dayIndex] = updatedDay;
    setReport(updatedReport);
  };

  const handleAutoGenerateDay = async (newDay) => {
    if (!report) return;

    const updatedReport = { ...report };
    updatedReport.days.push(newDay);
    setReport(updatedReport);
  };

  const handleDeleteDay = (dayIndex) => {
    if (!report) return;

    const updatedReport = { ...report };
    updatedReport.days.splice(dayIndex, 1);
    const totalHours = updatedReport.days.reduce((sum, d) => sum + (d.hours || 0), 0);
    updatedReport.total_hours = totalHours;
    setReport(updatedReport);
  };

  const stats = report ? getReportStats(report.days) : null;

  if (loading) {
    return <div style={{ padding: T.space.xl }}>Loading...</div>;
  }

  if (!report) {
    return <div style={{ padding: T.space.xl }}>Report not found</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', backgroundColor: T.bg.secondary }}>
      <Header isMobile={isMobile} />

      <main style={{
        flex: 1,
        padding: isMobile ? `${T.space.lg} ${T.space.md}` : `${T.space.xl}`,
        maxWidth: isMobile ? '100%' : '1000px',
        margin: '0 auto',
        width: '100%',
        paddingBottom: isMobile ? '80px' : T.space.xl,
      }}>
        {/* Title Section */}
        <div style={{
          marginBottom: isMobile ? T.space.lg : T.space.xl,
          backgroundColor: T.bg.primary,
          padding: isMobile ? T.space.lg : T.space.xl,
          borderRadius: T.radius.lg,
          boxShadow: T.shadow.sm,
        }}>
          <input
            type="text"
            value={report.title}
            onChange={(e) => setReport({ ...report, title: e.target.value })}
            style={{
              fontSize: isMobile ? T.size.lg : T.size.xxxl,
              fontWeight: 700,
              border: 'none',
              background: 'transparent',
              color: T.text.primary,
              width: '100%',
              padding: 0,
              outline: 'none',
              fontFamily: T.font.display,
              marginBottom: T.space.md,
            }}
          />

          {/* Stats */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: isMobile ? '1fr 1fr 1fr' : '1fr 1fr 1fr 1fr',
            gap: isMobile ? T.space.sm : T.space.md,
          }}>
            <div>
              <div style={{ fontSize: T.size.xs, color: T.text.secondary, fontWeight: 600, marginBottom: T.space.xs }}>
                Total Hours
              </div>
              <div style={{ fontSize: T.size.xl, fontWeight: 700, color: T.primary }}>
                {stats?.total || 0}h
              </div>
            </div>
            <div>
              <div style={{ fontSize: T.size.xs, color: T.text.secondary, fontWeight: 600, marginBottom: T.space.xs }}>
                Days
              </div>
              <div style={{ fontSize: T.size.xl, fontWeight: 700, color: T.primary }}>
                {report.days?.length || 0}
              </div>
            </div>
            <div>
              <div style={{ fontSize: T.size.xs, color: T.text.secondary, fontWeight: 600, marginBottom: T.space.xs }}>
                Holidays
              </div>
              <div style={{ fontSize: T.size.xl, fontWeight: 700, color: T.accent }}>
                {stats?.holidays || 0}
              </div>
            </div>
            {saveStatus !== 'idle' && (
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: T.space.sm,
                fontSize: T.size.sm,
                color: saveStatus === 'saving' ? T.text.secondary : T.success,
              }}>
                {saveStatus === 'saving' && (
                  <div style={{
                    width: 12,
                    height: 12,
                    borderRadius: '50%',
                    border: `2px solid ${T.text.secondary}`,
                    borderTopColor: 'transparent',
                    animation: 'spin 0.8s linear infinite',
                  }} />
                )}
                {saveStatus === 'saved' && <span>✓</span>}
                {saveStatus}
              </div>
            )}
          </div>
        </div>

        {/* Days Grid */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: isMobile ? '1fr' : 'repeat(auto-fill, minmax(280px, 1fr))',
          gap: isMobile ? T.space.md : T.space.lg,
        }}>
          {report.days && report.days.map((day, index) => (
            <div key={index} style={{ position: 'relative' }}>
              <DayInput
                reportId={reportId}
                day={day}
                dayIndex={index}
                nextDay={report.days?.[index + 1]}
                onUpdate={handleDayUpdate}
                onAutoGenerate={handleAutoGenerateDay}
                isMobile={isMobile}
              />
              {index > 0 && (
                <button
                  onClick={() => handleDeleteDay(index)}
                  style={{
                    position: 'absolute',
                    top: T.space.md,
                    right: T.space.md,
                    background: '#fee2e2',
                    color: T.error,
                    border: 'none',
                    borderRadius: T.radius.md,
                    padding: `${T.space.sm} ${T.space.md}`,
                    fontSize: T.size.xs,
                    cursor: 'pointer',
                    minHeight: T.touchTarget,
                    minWidth: T.touchTarget,
                  }}
                  title="Delete day"
                >
                  ✕
                </button>
              )}
            </div>
          ))}
        </div>

        {/* Add Day Button */}
        <button
          onClick={() => {
            const newDay = generateAutoDay(formatDate(new Date()));
            handleAutoGenerateDay(newDay);
          }}
          style={{
            marginTop: isMobile ? T.space.xl : T.space.xxl,
            padding: isMobile ? `${T.space.md} ${T.space.lg}` : `${T.space.md} ${T.space.xl}`,
            background: T.success,
            color: T.text.inverse,
            border: 'none',
            borderRadius: T.radius.md,
            fontSize: isMobile ? T.size.md : T.size.base,
            fontWeight: 600,
            cursor: 'pointer',
            transition: T.transition,
            minHeight: isMobile ? T.touchTarget : 'auto',
            width: isMobile ? '100%' : 'auto',
          }}
          onMouseEnter={(e) => !isMobile && (e.target.style.opacity = '0.9')}
          onMouseLeave={(e) => !isMobile && (e.target.style.opacity = '1')}
        >
          + Add Day
        </button>
      </main>

      {/* Mobile Bottom Action Bar */}
      {isMobile && (
        <div style={{
          position: 'fixed',
          bottom: 0,
          left: 0,
          right: 0,
          padding: T.space.md,
          background: T.bg.primary,
          borderTop: `1px solid ${T.border}`,
          paddingBottom: `calc(${T.space.md} + env(safe-area-inset-bottom))`,
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: T.space.sm,
          zIndex: 50,
        }}>
          <button
            onClick={() => (window.location.href = '/')}
            style={{
              padding: `${T.space.md} ${T.space.md}`,
              background: T.bg.secondary,
              color: T.text.primary,
              border: `1px solid ${T.border}`,
              borderRadius: T.radius.md,
              fontSize: T.size.sm,
              fontWeight: 600,
              cursor: 'pointer',
              minHeight: T.touchTarget,
            }}
          >
            ← Back
          </button>
          <button
            onClick={() => (window.location.href = '/')}
            style={{
              padding: `${T.space.md} ${T.space.md}`,
              background: T.primary,
              color: T.text.inverse,
              border: 'none',
              borderRadius: T.radius.md,
              fontSize: T.size.sm,
              fontWeight: 600,
              cursor: 'pointer',
              minHeight: T.touchTarget,
            }}
          >
            Save & Exit
          </button>
        </div>
      )}
    </div>
  );
}
